### ISSUE TITLE
Packing and unpacking of strings longer than 32 characters.

### ISSUE THREAD

**Issue by ravishankarachanta** [msgpack/msgpack#156]
I'm using MessagePack for developing a client SDK. I need to develop clients in java, ObjC and python while my server is in java. I don't have any problems with java and ObjC msgpack libraries but in python, when I pack a dictionary with string value longer than 31 characters, the packed data won't unpack in other languages. Trying to unpack the same in python works fine though and as long as the string length is less than 32, the inter operability is very fine too. The below is one python example that fails..

```
myPacket = {u"api_key":u"ad09739ac168ff2a199fb24eb4e24db8"}
msgPackedPacket = umsgpack.packb(myPacket)
```

the binary data generated for this is 

```
<81a76170 695f6b65 79d92061 64303937 33396163 31363866 66326131 39396662 32346562 34653234 646238>
```

while if I covert a dictionary with same key values in ObjC, I get 

```
<81a76170 695f6b65 79da0020 61643039 37333961 63313638 66663261 31393966 62323465 62346532 34646238>
```

The ObjC result unpacks fine and the python won't.. and you can note the 2 extra bytes in data from ObjC.

A properly working example as below

```
myPacket = {u"api_key":u"ad09739ac168ff2a199fb24eb4e24d"}  
```

number of characters = 30 here.. and I get the following bytes in python 

```
<81a76170 695f6b65 79be6164 30393733 39616331 36386666 32613139 39666232 34656234 65323464>
```

and for ObjC, I get the below bytes..

```
<81a76170 695f6b65 79be6164 30393733 39616331 36386666 32613139 39666232 34656234 65323464>
```

I have asked this in StackOverflow and the below is a link to it..

http://stackoverflow.com/questions/19466343/msgpack-packing-of-string-values-longer-than-32-characters-in-python

The answer from Tim Pietzcker in SO analyses the issue in detail.  

I'm sorry if I miss something obvious.. looking for any workarounds or suggestions.

Thanks in advance.

**Comment by ginahagg** [comment]
I am having the same problem with clojure msgpack implementation. it is packing str8 for serialization and erlang can't unpack it. Can you add compatibility switch force clojure-msgpack to create str16 for serialization
