### ISSUE TITLE
Proposal: Indexed string extension type

### ISSUE THREAD

**Issue by jblazquez** [msgpack/msgpack#160]
I'd like to gauge interest in a proposal to add an indexed string extension type to the MessagePack specification.

As the website says, MessagePack is a much more compact representation than JSON. This is true for all data types except one: strings. This proposal would add a more compact representation for strings that appear multiple times in a MessagePack stream by replacing them with an _index_ into a _dictionary_ that has been previously established.

As a motivating example, consider this typical JSON document from the Wikipedia article on JSON:

``` javascript
{
    "firstName": "John",
    "lastName": "Smith",
    "age": 25,
    "address": {
        "streetAddress": "21 2nd Street",
        "city": "New York",
        "state": "NY",
        "postalCode": 10021
    },
    "phoneNumbers": [
        {
            "type": "home",
            "number": "212 555-1234"
        },
        {
            "type": "fax",
            "number": "646 555-4567"
        }
    ]
}
```

If you're going to serialize many thousands of objects with a format similar to the above, having to repeat map keys such as "firstName" and "phoneNumbers" for each object leads to a lot of duplicated data. On the other hand, if you built a dictionary like the following:

``` javascript
[
    "firstName",
    "lastName",
    "age",
    "address",
    "streetAddress",
    "city",
    "state",
    "postalCode",
    "phoneNumbers",
    "type",
    "number",
    "home",
    "fax"
]
```

You could consider generating the following pseudo-JSON document which replaces strings with indices into the dictionary above:

``` javascript
{
    $0: "John",
    $1: "Smith",
    $2: 25,
    $3: {
        $4: "21 2nd Street",
        $5: "New York",
        $6: "NY",
        $7: 10021
    },
    $8: [
        {
            $9: $11.
            $10: "212 555-1234"
        },
        {
            $9: $12,
            $10: "646 555-4567"
        }
    ]
}
```

The use of indexed strings can result in large space savings when serializing many similar objects.

This proposal does not attempt to be a generic compression scheme for MessagePack documents. It only presents a solution for reducing the space requirements of duplicated strings - which can represent a large chunk of some MessagePack streams - without changes to other data types. An external compression algorithm applied to a MessagePack document will probably result in better space savings since it will be able to remove duplicated values of other types too, but no compression algorithms are currently part of the MessagePack specification. This proposal, if accepted, would allow for space savings in large MessagePack streams without the need for external compression.

**Updated proposal (12/13/2013):**

This proposal presents two new extension types that implement the indexed string concept: _dictionary string_ and _string reference_.

The dictionary string type represents a string that is likely to appear multiple times later in the stream. It prompts the deserializer to store this string in a _dictionary_ so that it can be looked up later when referenced.

The string reference type represents a _reference_ to a previously-encountered string that has been added to the dictionary. This type consists of a single _index_ value that identifies which entry in the dictionary this element refers to. A deserializer that processes this type shall substitute the value with the referenced dictionary string. The effect is exactly as if the original string had been emitted in place of the reference value.

The proposed encoding for dictionary strings would be the following (assuming this extension has been assigned type -1):

```
dictstr 8 represents a dictionary string whose length is up to (2^8)-1 bytes:
+--------+--------+--------+========+
|  0xd4  |   -1   |XXXXXXXX|  data  |
+--------+--------+--------+========+

dictstr 16 represents a dictionary string whose length is up to (2^16)-1 bytes:
+--------+--------+--------+--------+========+
|  0xd5  |   -1   |YYYYYYYY|YYYYYYYY|  data  |
+--------+--------+--------+--------+========+

dictstr 32 represents an indexed string whose length is up to (2^32)-1 bytes:
+--------+--------+--------+--------+--------+--------+========+
|  0xd6  |   -1   |ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|  data  |
+--------+--------+--------+--------+--------+--------+========+

where
* XXXXXXXX is an 8-bit unsigned integer which represents N
* YYYYYYYY_YYYYYYYY is a 16-bit big-endian unsigned integer which represents N
* ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ is a big-endian 32-bit unsigned integer which represents N
* N is the length of data
* data is the byte array that represents the string in UTF-8 encoding
```

After encountering a dictstr element, the deserializer shall append the string to the end of the dictionary.

The proposed encoding for string references would be the following (assuming this extension has been assigned type -2):

```
strref 8 represents a string reference whose index is between [-2^7, 2^7):
+--------+--------+--------+
|  0xd4  |   -2   |XXXXXXXX|
+--------+--------+--------+

strref 16 represents a string reference whose index is between [-2^15, 2^15):
+--------+--------+--------+--------+
|  0xd5  |   -2   |YYYYYYYY|YYYYYYYY|
+--------+--------+--------+--------+

strref 32 represents a string reference whose index is between [-2^31, 2^31):
+--------+--------+--------+--------+--------+--------+
|  0xd6  |   -2   |ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|
+--------+--------+--------+--------+--------+--------+

where
* XXXXXXXX is an 8-bit signed integer which represents IDX
* YYYYYYYY_YYYYYYYY is a 16-bit big-endian signed integer which represents IDX
* ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ is a big-endian 32-bit signed integer which represents IDX
* IDX is the index of the string into the dictionary
```

The interpretation of a strref value is as follows:
- If the index _i_ is negative, the value represented by the strref element is the _ith_ preceding dictionary string in the stream, or put another way, the _ith_ string in the _stream dictionary_ starting from the end. An index of -1 refers to the last string in the stream dictionary, and index of -2 refers to the second-to-last, and so on.
- If the index _i_ is positive, the value represented by the strref element is the _ith_ string in the _root dictionary_, where the first string has index 0. As opposed to the stream dictionary - which consists of dictionary strings encountered during deserialization - the root dictionary is optional and externally provided to the deserializer. It is not serialized as part of the stream. 

The rationale for allowing a root dictionary that is not part of the MessagePack stream is for applications that use a well-known static dictionary for serialization or who wish to send the dictionary separately, perhaps in preparation for a large number of MessagePack streams that are serialized and stored separately and which would otherwise need to each include a copy of the dictionary strings they all share.

The rationale for referencing strings in the stream dictionary using negative indices is to allow for already-serialized MessagePack streams to be easily appended as children of larger MessagePack streams without having to modify them. The use of negative indices avoids having those MessagePack substreams change their meaning depending on the context to which they've been appended to.

**Original proposal:**

This proposal presents a new _indexed string_ extension type that replaces a string value with an index into the current dictionary in scope. A dictionary can be established in a given scope by using an _indexed document_ extension type that prepends the desired dictionary to a MessagePack document. The dictionary would then be in scope and usable by indexed string values within that document. Alternatively, the dictionary could be implicit (perhaps sent separately, or known intimately by the application) and would need to be known to the reader in order to resolve indexed strings in the stream.

The proposed encoding for indexed strings would be the following (assuming this extension has been assigned type -1):

```
stridx 1 represents an indexed string whose index is up to (2^8)-1:
+--------+--------+--------+
|  0xd4  |   -1   |XXXXXXXX|
+--------+--------+--------+

stridx 2 represents an indexed string whose index is up to (2^16)-1:
+--------+--------+--------+--------+
|  0xd5  |   -1   |YYYYYYYY|YYYYYYYY|
+--------+--------+--------+--------+

stridx 4 represents an indexed string whose index is up to (2^32)-1:
+--------+--------+--------+--------+--------+--------+
|  0xd6  |   -1   |ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|
+--------+--------+--------+--------+--------+--------+

where
* XXXXXXXX is an 8-bit unsigned integer which represents IDX
* YYYYYYYY_YYYYYYYY is a 16-bit big-endian unsigned integer which represents IDX
* ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ is a big-endian 32-bit unsigned integer which represents IDX
* IDX is the zero-based index of the string into the dictionary
```

The interpretation of an stridx value is as follows:
- The value represented by an stridx element is the string located at the specified zero-based _index_ into the current _dictionary_ in scope.
- A dictionary is an array of string values, the first of which is considered to be at index 0.
- A dictionary must be established in the current _scope_ in order for stridx elements to be valid. stridx elements refer only to the current dictionary in scope.
- Dictionaries can be established in a scope using an _indexed document_ element.
- A dictionary can also be established in the root scope so that stridx values that appear outside of indexed document elements can resolve their values against it.

An indexed document is simply a combination of an arbitrary MessagePack document with an associated dictionary used to resolve stridx values that appear in that document. When a reader encounters an indexed document element, the contents of the embedded document are considered to be logically placed at the same location in the MessagePack tree as the indexed document element itself. In other words, the indexed document element does not become a part of the logical MessagePack document; its contents - with all stridx elements having been resolved to their corresponding strings - do so instead. To illustrate, the logical MessagePack tree below:

``` javascript
{
    "company": "Riot Games",
    "employees": <<indexed document: (dictionary) [
        { $0: ... },
        { $0: ... },
        { $0: ... }
    ]>>
}
```

Becomes the following after processing the indexed document element and resolving indexed strings in it:

``` javascript
{
    "company": "Riot Games",
    "employees": [
        { "name": ... },
        { "name": ... },
        { "name": ... }
    ]
}
```

The proposed encoding for indexed document elements would be the following (assuming this extension has been assigned type -2):

```
idxdoc 8 stores a dictionary and a MessagePack stream whose combined length is up to (2^8)-1 bytes:
+--------+--------+--------+========+========+
|  0xc7  |XXXXXXXX|   -2   |  dict  |  data  |
+--------+--------+--------+========+========+

idxdoc 16 stores a dictionary and a MessagePack stream whose combined length is up to (2^16)-1 bytes:
+--------+--------+--------+--------+========+========+
|  0xc8  |YYYYYYYY|YYYYYYYY|   -2   |  dict  |  data  |
+--------+--------+--------+--------+========+========+

idxdoc 32 stores a dictionary and a MessagePack stream whose combined length is up to (2^32)-1 bytes:
+--------+--------+--------+--------+--------+--------+========+========+
|  0xc9  |ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|   -2   |  dict  |  data  |
+--------+--------+--------+--------+--------+--------+========+========+

where
* dict is a dictionary of type array or fixarray
* data is any valid MessagePack type
* XXXXXXXX is an 8-bit unsigned integer which represents N
* YYYYYYYY_YYYYYYYY is a 16-bit big-endian unsigned integer which represents N
* ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ_ZZZZZZZZ is a big-endian 32-bit unsigned integer which represents N
* N is the combined length of dict + data in bytes
```

The rationale for having this indexed document type is to allow for dictionaries to be embedded in the MessagePack stream directly without having to send it separately. It also allows for already-serialized MessagePack documents to be easily appended as children of larger MessagePack documents (without having to modify them) by including the dictionary that they have been serialized with.

The rationale for allowing an implicit root dictionary that is not part of the MessagePack stream is to allow for applications that use a well-known static dictionary for serialization or who wish to send the dictionary separately, perhaps in preparation for a large number of MessagePack documents that are serialized and stored separately and which would otherwise need to each include a copy of the dictionary they all share.

This is the proposal. I would appreciate any comments or concerns.

A few things that I've been thinking about:
- Indexed documents can embed arbitrary MessagePack streams, but those streams will almost always be an array or a map. Should we have _indexed array_ and _indexed map_ extension types instead?
- I don't really like the name "indexed document" but I couldn't come up with a better one. The idea is that it's an embedded dictionary and a MessagePack document which can contain indexed strings into that dictionary.

**Comment by matthijskooijman** [comment]
I'm also interested in this feature. The last comment here is old (2013), but suggested that a feature like this is first implemented using the ext-format as a user extension, to maybe later be incorporated in the spec.

Does anyone know if any such ext-format-based implementations have been made that can be used right now to get this feature?
