### ISSUE TITLE
Why is MsgPack big endian?

### ISSUE THREAD

**Issue by DaveVdE** [msgpack/msgpack#172]
Not really an issue per se, but I'm writing a small encoder/decoder and I must say, it's a pain having to tansform all my in-memory representations of ints, floats from little-endian to big-endian.

Is it deliberate? Is it an optimization for smaller (possibly big-endian) mobile platforms? I care to know.

**Comment by Tronic** [comment]
Sorry to post to a very old thread, but just for the public record:

Any *new* formats should really be little endian. The network convention is dead and no CPUs use big endian anymore. Little endian buffers work directly on current CPUs and are much easier to handle whenever a byte at a time needs processing (avoids some backwards for loops that you need with big endian).
