### ISSUE TITLE
how to splite msgpack package when recieve data stram over TCP?

### ISSUE THREAD

**Issue by FindNemo** [msgpack/msgpack#192]
Did I need to add custom special hex data before and after every msgpack package? Just like sending strcut binary data in C language over TCP?

**Comment by methane** [comment]
Use streaming unpacker.
https://github.com/msgpack/msgpack-python#streaming-unpacking

**Comment by FindNemo** [comment]
thanks a lot

**Comment by kuenishi** [comment]
Hope your problem was solved.
