### ISSUE TITLE
Is there a guide about what is changed in v5 spec?

### ISSUE THREAD

**Issue by laruence** [msgpack/msgpack#193]
thanks

**Comment by methane** [comment]
See #162 
There aren't v5

**Comment by methane** [comment]
There are the spec and old spec.
No version number means no more update, I think.

**Comment by methane** [comment]
Changes in format are:

* raw => str
* str 8 was added (old spec doesn't have raw8)
* bin and ext were added

**Comment by laruence** [comment]
hmm, thanks. :)
