### ISSUE TITLE
Missing optional field of object in list leads to exception at deserialization

### ISSUE THREAD

**Issue by lmenzel** [msgpack/msgpack#220]
After adding an new optional property to an object (contained in a list), the serialized data can not be deserialized anymore, an serialization exception is thrown. This happens only, if the object is in a list. The same object can be deserialized after adding that property without any problems, if it is not in a list.
We are using MsgPack.Cli 0.8.0
Attached you find some unit tests that can reproduce it and the exception that is thrown.
[SerializationException.txt](https://github.com/msgpack/msgpack/files/592580/SerializationException.txt)
[MessagePackTest.cs.txt](https://github.com/msgpack/msgpack/files/592590/MessagePackTest.cs.txt)

**Comment by mlsomers** [comment]
You could try using [MsgPack Explorer](http://www.infotopie.nl/open-source/msgpack-explorer) to check if the serialized package is valid (rule out if the error is in the serialization or deserialization).

**Comment by lmenzel** [comment]
We found the problem: The MsgPack.Cli uses SerializationMethod "array" as default, not as we understood from the documentation:
"SerializationMethod controls behavior of generated serializers that they pack object properties/fields with array type (default, de-facto standard, and more efficient) or map type (more version torrelant, and the **default of MessagePack C#**)."

So using the "map" method helped: Then it is no problem to add a field.
SerializationContext.Default.SerializationMethod = SerializationMethod.Map;
