### ISSUE TITLE
MsgPack big endian?

### ISSUE THREAD

**Issue by rfyiamcool** [msgpack/msgpack#230]
Not really an issue per se, but I'm writing a small encoder/decoder and I must say, it's a pain having to tansform all my in-memory representations of ints, floats from little-endian to big-endian.

**Comment by drewnoakes** [comment]
Looks like a duplicate of #172.

**Comment by tagomoris** [comment]
See https://github.com/msgpack/msgpack/issues/172#issuecomment-40641830
