### ISSUE TITLE
Broken markdown formatting in spec.md

### ISSUE THREAD

**Issue by catnapgames** [msgpack/msgpack#231]
When viewing spec.md here on Github I see broken h2 titles after table of contents - Type System and from there on.

![screen shot 2017-07-10 at 14 02 48](https://user-images.githubusercontent.com/1115711/28017233-97a72dc2-6578-11e7-884c-1bca2fb2a134.png)

**Comment by drewnoakes** [comment]
Seems ok now:

![image](https://user-images.githubusercontent.com/350947/31934492-25edb7ee-b8a4-11e7-8716-8e322988993b.png)

**Comment by tagomoris** [comment]
I fixed it at #234.
