### ISSUE TITLE
hope :

### ISSUE THREAD

**Issue by ugksoft** [msgpack/msgpack#232]
1.grid data 
sg:
 name,sex,mail
 abc   0    abc@abc.com
 def   1   def@def.com
pack->
name,Bool:sex,mail, abc   0    abc@abc.com, def   1   def@def.com
(TitleFlag,Len_3,TitleData,Data_Flag,Len_2,Data.....)

2. noname
sg:
data1,data2,data3,data4 ,   NewRowFlag
data5,data6,                        NewRowFlag
data7,data8,data9,data10   DataSegEndFlag
DataA,DataB,DataC....

3. CRCFlag
CRCType,CRCDataLen,CRCValue
CRCType 4bit or 1byte: crc8,crc16,crc32,md5,sha1,sha2.... UserCRCType

5.encrypt/codes
enType,enDataLen,enCRC

6.DataVerFlag

**Comment by tagomoris** [comment]
I can't see what you mean. Could you describe what you want in English?
(Otherwise, I'll close this issue later.)

**Comment by ugksoft** [comment]
# **Recommend new packaging methods**

1.for DataBase Record
execsql:  select * from user;

josn,msgpack,xml....methon:
{   
    name:abc,sex:0,mail:abc@abc.com
    name:def,sex:1,mail:def@def.com
    ,,,
   ,,,,
}
->  new method,
msgpack,json,xml:
{
   title: Name,Sex,Mail            //nameField only once
    abc,0,abc@abc.com
   def,1,def@def.com
}

3.no Name Field, onlydata
 Data1,data2,data3,data4... RowEndFlag
 Data5,Data6,RowEndFlag
 Data7,Data8,Data9,Data10 RowEndFlag
4. DataCRCFlag
  CRCType CRCDataLen,CRCValue  //
5.encrypt Flag
 EndType,EndDataLen,EnCRC
6.DataVerFlag


------------------------------------------------------------------
sorry.我不会说英语

1.数据库表格,
execsql:  select * from user;

{   太浪费了
    name:abc,sex:0,mail:abc@abc.com
    name:def,sex:1,mail:def@def.com
    ,,,
   ,,,,
}
->  节省
msgpack,json,xml:
{
   title: Name,Sex,Mail
    abc,0,abc@abc.com
   def,1,def@def.com
}

3.不需要名字的数据
 Data1,data2,data3,data4... RowEndFlag
 Data5,Data6,RowEndFlag
 Data7,Data8,Data9,Data10 RowEndFlag
4.CRC标记
  CRCType CRCDataLen,CRCValue
5.加密方法
 EndType,EndDataLen,EnCRC
6.数据版本标记

**Comment by dchenk** [comment]
This is clearly spam, should be closed and deleted.
