### ISSUE TITLE
Change output format for binary data in YAML

### ISSUE THREAD

**Issue by Mons** [msgpack/msgpack#238]
Currently binary data are formatted as
```yaml
tarantool> "\x00\x01\x02\x03\x04\x05\x06\xff"
---
- !!binary AAECAwQFBv8=
...
```

The propose is to output ASCII as is and everything outside [0x20..0x7f] as "\x%02X"
This would be usable either in Lua or in YAML.

**Comment by tagomoris** [comment]
It's not about msgpack.
