### ISSUE TITLE
JSON twice smaller than msgpack

### ISSUE THREAD

**Issue by archenroot** [msgpack/msgpack#242]
I got to msgpack today to test some hands-on dummy scenarios and was surprised with opposite than presented result on my first scenario  :-))

Here are results:
-rw-r--r--  1 zangetsu zangetsu 149217 Feb 21 14:33 msgpack.dat
-rw-r--r--  1 zangetsu zangetsu  20309 Feb 21 14:44 msgpack.dat.xz.7z
-rw-r--r--  1 zangetsu zangetsu  75669 Feb 21 14:33 sample.json
-rw-r--r--  1 zangetsu zangetsu  15353 Feb 21 14:44 sample.json.xz.7z

All files are attached, both data should be 1:1:
[sample.msgpack.txt](https://github.com/msgpack/msgpack/files/1744175/sample.msgpack.txt)
[sample.json.txt](https://github.com/msgpack/msgpack/files/1744177/sample.json.txt)

I understand msgpack is base on more simple design, but being 2x bigger than JSON was unexpected. What is the root cause, do you have any tools to analyze root cause, something like in DB system query execution plan to see what is the situation which doesn't drop much?

**Comment by tagomoris** [comment]
The file of 149217bytes seems to be represented in hex-dumped "text" file, not binary msgpack format.
It is NOT msgpack itself.

**Comment by archenroot** [comment]
Sorry, my bad, thx for clarification.

**Comment by archenroot** [comment]
Still the format after convertion to bracketed binary is about 30% more... or am I doing something more?

**Comment by archenroot** [comment]
[sample.msgpack.txt](https://github.com/msgpack/msgpack/files/1744339/sample.msgpack.txt)

```
drwxr-xr-x  8 zangetsu zangetsu   4096 Feb 21 15:10 msgpack-java
drwxr-xr-x  9 zangetsu zangetsu   4096 Feb 21 15:04 msgpack-tools
-rw-r--r--  1 zangetsu zangetsu  20309 Feb 21 14:44 msgpack.dat.xz.7z
-rw-r--r--  1 zangetsu zangetsu  75669 Feb 21 14:33 sample.json.txt
-rw-r--r--  1 zangetsu zangetsu  15353 Feb 21 14:44 sample.json.xz.7z
-rw-r--r--  1 zangetsu zangetsu 104339 Feb 21 15:34 sample.msgpack.txt

```

**Comment by methane** [comment]
Please use valid example.
```
$ jq . < sample.json.txt
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 42, column 79
```

**Comment by archenroot** [comment]
@methane - I used https://www.json-generator.com/ with following default config to get some bigger file to play with:
```
[
  '{{repeat(5, 7)}}',
  {
    _id: '{{objectId()}}',
    index: '{{index()}}',
    guid: '{{guid()}}',
    isActive: '{{bool()}}',
    balance: '{{floating(1000, 4000, 2, "$0,0.00")}}',
    picture: 'http://placehold.it/32x32',
    age: '{{integer(20, 40)}}',
    eyeColor: '{{random("blue", "brown", "green")}}',
    name: '{{firstName()}} {{surname()}}',
    gender: '{{gender()}}',
    company: '{{company().toUpperCase()}}',
    email: '{{email()}}',
    phone: '+1 {{phone()}}',
    address: '{{integer(100, 999)}} {{street()}}, {{city()}}, {{state()}}, {{integer(100, 10000)}}',
    about: '{{lorem(1, "paragraphs")}}',
    registered: '{{date(new Date(2014, 0, 1), new Date(), "YYYY-MM-ddThh:mm:ss Z")}}',
    latitude: '{{floating(-90.000001, 90)}}',
    longitude: '{{floating(-180.000001, 180)}}',
    tags: [
      '{{repeat(7)}}',
      '{{lorem(1, "words")}}'
    ],
    friends: [
      '{{repeat(3)}}',
      {
        id: '{{index()}}',
        name: '{{firstName()}} {{surname()}}'
      }
    ],
    greeting: function (tags) {
      return 'Hello, ' + this.name + '! You have ' + tags.integer(1, 10) + ' unread messages.';
    },
    favoriteFruit: function (tags) {
      var fruits = ['apple', 'banana', 'strawberry'];
      return fruits[tags.integer(0, fruits.length - 1)];
    }
  }
]
```

I will test again with jq tool as you do....

**Comment by archenroot** [comment]
It is probably issue with generator because I get now (after some repeats change): 
`parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 20, column 135`
When using jq

**Comment by archenroot** [comment]
Funny thing is that if I put the content into some online validator it says: OK, so ... Otherwise I work on UTF-8 Linux system (Gentoo)

**Comment by archenroot** [comment]
I found it, it is in the end of line... of about field, I will fix and test again.

**Comment by archenroot** [comment]
Ok, thx for help on this final result is:
```
zangetsu@venus ~/devel/proj/tmp $ ls -la
total 88
drwxr-xr-x  4 zangetsu zangetsu  4096 Feb 21 17:14 .
drwxr-xr-x 17 zangetsu zangetsu  4096 Feb 21 14:31 ..
drwxr-xr-x  8 zangetsu zangetsu  4096 Feb 21 15:10 msgpack-java
drwxr-xr-x  9 zangetsu zangetsu  4096 Feb 21 15:04 msgpack-tools
-rw-r--r--  1 zangetsu zangetsu 34820 Feb 21 17:08 sample.json.txt
-rw-r--r--  1 zangetsu zangetsu  6624 Feb 21 17:14 sample.json.txt.xz.7z
-rw-r--r--  1 zangetsu zangetsu 19208 Feb 21 17:09 sample.msgpack.txt
-rw-r--r--  1 zangetsu zangetsu  6547 Feb 21 17:14 sample.msgpack.txt.xz.7z
```
