### ISSUE TITLE
XML serialization/deserialization support

### ISSUE THREAD

**Issue by oblomingo** [msgpack/msgpack#257]
I can't find any information about XML format serialization and deserialization. 
Does msgpack support XML? If yes, could you provide simple example?

**Comment by nebula0723** [comment]
NO strongly suggest that you take a look at this [https://github.com/qicosmos/iguana](url)
this lib support XML format serialization and deserialization.

**Comment by tagomoris** [comment]
The question is unclear. Which one are you asking?
* Does msgpack support serialization to XML / deserialization from XML?
* Does msgpack support serialization of data from XML to MessagePack?

Anyway, MessagePack itself doesn't support XML serialization/deserialization. See other solutions.
