### ISSUE TITLE
Invalid nil code while decode ext type

### ISSUE THREAD

**Issue by cedricfung** [msgpack/msgpack#262]
For a custom type, I defined the marshal and unmarshal method, the underlying data is []byte. The encoder produces data `c70500c09eec3100`, but the decoder failed to decode it.

`c7` means Ext8 type, `05` is the data length, `00` is the application custom type, `c09eec3100` is the actual data payload, with length `05`.

But the decoder tries to PeekCode for the payload `c09eec3100` at first, and the code `c0` is nil, so this decoder will fail.

```
func unmarshalValue(d *Decoder, v reflect.Value) error {
	if d.hasNilCode() {
		return d.decodeNilValue(v)
	}

	if v.IsNil() {
		v.Set(reflect.New(v.Type().Elem()))
	}

	if d.extLen != 0 {
```

**Comment by methane** [comment]
This issue tracker is about msgpack spec.
I don't know which library you're using, but use the library's issue tracker.  Not here.

**Comment by cedricfung** [comment]
Ooops, sorry for the wrong place.
