### ISSUE TITLE
how to deserialize to property of type object in c# annoted with xml attributes

### ISSUE THREAD

**Issue by nicoclau** [msgpack/msgpack#271]
we have  a property in c#

object item { get; set; }

when deserialized we got back messagepackobject with data of the expected object in json

How can we make the serializer create the expected object instead of the messagepackobject

the property is annotated with xml atttribute for all different types possible that the property can get in xml deserialization.

Thanks for your help

kind regard
nico

**Comment by mlsomers** [comment]
That depends on the library you are using. Would it by any chance be mine?
[https://github.com/mlsomers/LsMsgPack](https://github.com/mlsomers/LsMsgPack)

In that case you would do:
object item = MsgPackSerializer.Deserialize<ExpectedObjectType>(Stream or byte[] source);

**Comment by tagomoris** [comment]
This repository is of the spec of MessagePack. Please don't do Q&A here. There should be other better places for the usage of C# implementations.
Let me close this.
