### ISSUE TITLE
Performance Issues in Segmentation

### ISSUE THREAD

**Issue by anandology** [msgpack/msgpack#278]
This issue is created to track all the performance issues in segmentation and propose possible solutions.

## segments.plot

The `/segments.plot` API call is taking more than 10 seconds on the 100K dataset. Most of the time is spent in JSON serialization. This can be improved by switching to msgpack. Noticed at least 5X improvement in performance with that.

## clusters.create

Creating clusters is taking very long time. Not because of the computation, but due to the inefficiencies in the data layer.

It took about 15 minutes to compute the clusters for the 100K dataset with `num_clusters=9`.

**Comment by markusschaber** [comment]
Is this issue filed at the correct lace? Looks like it should be somewhere else...

**Comment by anandology** [comment]
Sorry, filed in the wrong repo. Closing it...
