### ISSUE TITLE
Messagepack cant deserialize ICollection, IEnumerable etc.

### ISSUE THREAD

**Issue by mvSapphire** [msgpack/msgpack#280]
**Issue**
For example, we have a Controller with POST endpoint that receives ICollection<int> as parameters, we got 415 Error response.

But if we change ICollection<int> to int[] everything works as expected.

My guess that messagePack serialize collections as an array and lose the c# type information and after that cant convert to specific interface back. But if use exact realization of these interfaces as a parameter (which realize array under the hood) messagePack deserialize well. 

Am I right? Or this is a bug in messagePack?

**Comment by tagomoris** [comment]
This repository is to discuss MessagePack's spec, not bugs, library features, etc.
Could you go to the repository (or issue tracker?) of MessagePack library you're using (C#)?

At least, it's not a bug of MessagePack spec (and IMHO it's not a bug of MessagePack-CSharp, but not sure).
