### ISSUE TITLE
heap out of memory

### ISSUE THREAD

**Issue by yanzhou-share** [msgpack/msgpack#282]
There are always the following mistakes. How can I solve them. thanks!

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x24441b25c01d]
Security context: 0x2acc78228d39 <JSObject>
    1: copy [0x2acca908f7e9] [/Users/mac/workspace/wb-server/node_modules/bl/bl.js:~138] [pc=0x24441b54db11](this=0x2accc0195b61 <BufferList map = 0x2acc1396ba29>,dst=0x2acc118822b1 <null>,dstStart=0,srcStart=54,srcEnd=55)
    2: tryDecode(aka tryDecode) [0x2acc1af8a4b1] [/Users/mac/workspace/wb-server/node_modules/msgpack5/lib/decoder.js:~112] [pc=0x24441b5...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by tagomoris** [comment]
This repository is about the spec of MessagPack, not about the implementation of MessagePack.
@yanzhou-share visit the repository of the implementation you're using (or any appropriate Q&A services) and ask your question.
