### ISSUE TITLE
Unpacking objects individually from a TCP stream

### ISSUE THREAD

**Issue by solub** [msgpack/msgpack#284]
Hi, I would like to know if it is possible to read one by one the objects coming from a TCP stream.

In the example below I am storing the data in a buffer after reception, then proceed to unpacking when the stream is over. My problem is that I need to unpack the tuples one by one **as they are sent**. In other words I would like to read the data **in real time** without putting it in a buffer.

Provided it is possible, how could I achieve this using MessagePack ?

_-- client side --_

```
#Python3.7
import socket
import msgpack
import math
    
HOST = "127.0.0.1"
PORT = 9000
    
den = 40
rad = 100
theta = math.tau / den
    
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    sock.connect((HOST, PORT)) #connect to server
    
    for step in range(den):
        x = math.cos(i*theta) * rad #computes a point location (tuple)
        y = math.sin(i*theta) * rad
        data = msgpack.packb((x, y), use_bin_type = True) #packs location
        sock.sendall(data) #send it through a socket

```

_-- server side --_

```
#Jython2.7 <-- Python 2.7 compatible only
from io import BytesIO
import msgpack
import socket
    
HOST = "127.0.0.1"
PORT = 9000
    
buf = BytesIO()
    
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(1)
connection, address = s.accept()
    
    
while True:
    try:
        data = connection.recv(1024)
        buf.write(data) #put data in a buffer
            
    except:
        buf.seek(0)
        unpacker = msgpack.Unpacker(buf, use_list=False, raw=False) #unpack
        for unpacked in unpacker:
            print(unpacked)
        buf = BytesIO()
```

**Comment by tagomoris** [comment]
From MessagePack spec's viewpoint, it's possible because MessagePack doesn't use footers.
But it depends on the library features if we can do it or not.
@solub Check the client library features you're using.

**Comment by solub** [comment]
Sorry to insist but would you mind to give a simple example ?

Also I don't quite understand your reply, what "library" are you referring
to (socket or io ?) and how would that matter in this case ?

I have posted this question
<https://stackoverflow.com/questions/62070555/unpacking-objects-individually-from-a-tcp-stream>
on Stackoverflow and no one could answer so far. You might be the only ones
to understand how to implement this real-time unpacking logic with
MessagePack so your help would be much appreciated.

**Comment by methane** [comment]
I ansswered it on SO.
