### ISSUE TITLE
Array of types : bloated

### ISSUE THREAD

**Issue by pfeatherstone** [msgpack/msgpack#285]
If we have an array (in this example a size up to 2^32 - 1) of floats you have: 
+--------+--------+--------+--------+--------+~~~~~~~~~~~~~~~~~+
|  0xdd  |ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|    N objects    |
+--------+--------+--------+--------+--------+~~~~~~~~~~~~~~~~~+
where the object is a float32.
Now a float32 is:
+--------+--------+--------+--------+--------+
|  0xca  |XXXXXXXX|XXXXXXXX|XXXXXXXX|XXXXXXXX|
+--------+--------+--------+--------+--------+
So the overall object has N copies of type prefix 0xca. This seems overkill since it's never going be any different.
Why not have a single type prefix after the array length? so:
+--------+--------------+--------------+--------------+--------------+--------+~~~~~~~~~~~~~~~~~+
|  0xdd  |ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|  0xca  |  N * (objects - prefix)   |
+--------+--------------+--------------+--------------+--------------+--------+~~~~~~~~~~~~~~~~~+
This would avoid necessary padding of O(N)

**Comment by AtjonTV** [comment]
And how do you suggest one would handle mixed arrays? say you have 20 floats followed by 15 integers and 8 strings ..

It seems strange to me to limit a array to one type when it was planned to have all types at once.

**Comment by pfeatherstone** [comment]
Yes sorry, i should have closed this issue ages ago. I wasn't  aware at the time that msgpack supported different types within an array.
