### ISSUE TITLE
Does msgpack support pack str in specific length?

### ISSUE THREAD

**Issue by miaogen123** [msgpack/msgpack#290]
Here is a circumstance: I have a extracter, which is compiled with msgpack-c:0.5.7.3 supporting packing str in the length of 31/2^16-1/2^32-1, but packer is compiled with msgpack-c:3.0.x，which supports packing with 31/255/2^16-1/2^32-1。
when str length is between [32,255], extracter fail to extract because of mismatch prefix.
Is it possible to pack str within [32,255] with prefix of str of length 2^16-1？I didn't find any interface alike in the 3.0.x source codes

**Comment by tagomoris** [comment]
It should be specifically about msgpack-c. Is it?

**Comment by miaogen123** [comment]
You're right

**Comment by tagomoris** [comment]
OK. Please visit the Q&A site or issue trackers of that library for your problem.
This is the repository about MessagePack specs, not the implementations. Let me close this issue now.
