### ISSUE TITLE
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/msgpack-1.4.1/lib/msgpack.rb:8:in `require': 

### ISSUE THREAD

**Issue by AaronYin0514** [msgpack/msgpack#294]
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/msgpack-1.4.1/lib/msgpack.rb:8:in `require': dlopen(path.../.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/msgpack-1.4.1/lib/msgpack/msgpack.bundle, 9): no suitable image found.  Did find: (LoadError)

**Comment by tagomoris** [comment]
Here is the repository about the spec of MessagePack.
Could you report it on the repository of the implementation (probably it's of msgpack-ruby)?
