### ISSUE TITLE
List of companies using MessagePack in production

### ISSUE THREAD

**Issue by jviotti** [msgpack/msgpack#295]
Are we keeping a list of companies using MessagePack in production somewhere? The [landing page](https://msgpack.org) lists some, but its not very extensive.

I'm particularly interested in a small list of companies for research purposes (I'm writing a paper involving MessagePack and discussing some of its history and industry use).

**Comment by markusschaber** [comment]
We're using MessagePack in one of our products. Depending on what information you need, and what the purpose and audience of the paper is, I may get permission to reveal some details.
