### ISSUE TITLE
Show: Papers covering MessagePack

### ISSUE THREAD

**Issue by jviotti** [msgpack/msgpack#316]
Hey there!

As part of my MSc dissertation at University of Oxford, I wrote and published two papers covering the characteristics of various binary serialization formats, including MessagePack and performing a space-efficiency benchmark, respectively.

Sharing them here in case anybody finds them interesting! The first paper explains how MessagePack works including an annotated hexadecimal example and the second compares MessagePack to various other popular serialization formats.

- A Survey of JSON-compatible Binary Serialization Specifications: https://arxiv.org/abs/2201.02089
- A Benchmark of JSON-compatible Binary Serialization Specifications: https://arxiv.org/abs/2201.03051

All the best!

**Comment by mlsomers** [comment]
Thank you!
This kind or research is really valuable!
Once doing professional development, research becomes far too costly and time consuming to do within a projects budget.

**Comment by jviotti** [comment]
Closing this issue. It has been opened for a while and served its purpose. Probably no need to have it open forever :) Thanks a lot!
