### ISSUE TITLE
Encoding order for hashmaps

### ISSUE THREAD

**Issue by mimoo** [msgpack/msgpack#317]
Hello. I am looking for a deterministic encoding: something that always encode a struct in the same series of bytes (for cryptographic purposes). It seems to me that since msgpack encoding is untagged, most things should be deterministic. But for hashmaps, I don’t see any insurance on the ordering encoding of the entries. Am I right that this makes messagepack not deterministic? Are there other non-deterministic corners? Thanks!

**Comment by methane** [comment]
Officially, no. I don't guarantee any determinism. Do not think I never change output binary in future versions.

Technically, and as I remember, current msgpack implementation is deterministic.
For maps, msgpack uses just Python's dict order. When dict order is same, output is same.

**Comment by tagomoris** [comment]
The spec of `map` defines its expression - the series of key-value pairs. Thus, it has the order.

I guess you're using a language that encodes/decodes `map` into `HashMap` (like Java), which doesn't have the order of entries. In other languages with ordered map-like objects, the order will be preserved after encoding/decoding `map` objects.

For example in Ruby:
```
irb(main):001:0> require 'msgpack'
=> true
irb(main):002:0> h1 = {"a" => 1, "b" => 2, "c" => 3}
=> {"a"=>1, "b"=>2, "c"=>3}
irb(main):003:0> MessagePack.load(MessagePack.dump(h1))
=> {"a"=>1, "b"=>2, "c"=>3}
```

`HashMap`'s non-preserved entry order (if you're surely using Java and `HashMap`) is its own characteristic, not of MessagePack.

If you want to use ordered `Map`-like objects in Java, using `TreeMap` with an extension type could be a solution.
For more details, please refer the document of MessagePack library you're using.

**Comment by mimoo** [comment]
I'm actually using Rust, but same issue there I don't think there's any assurance on ordering. Note that I'm now using [BCS](https://github.com/diem/bcs) which looks like it was designed for my use case. Thanks!
