### ISSUE TITLE
Runtime equivalent of Struct

### ISSUE THREAD

**Issue by jdevng** [msgpack/msgpack#335]
Is there a way to use run time dictionaries and arrays as input instead of the Codeable structs? Or any method where types/structures of the messages can be defined at run time like in Python? Thanks!

**Comment by mlsomers** [comment]
Nothing in the specs mandate anything about strongly typing, "stringly-typing" or duck-typing...
It is up to the implementation of the spec in the library you are using what it supports or not.
Maybe you are asking the question in the wrong place.
