### ISSUE TITLE
Timestamp nanoseconds that are larger than 1 billion are not allowed by the spec.

### ISSUE THREAD

**Issue by junderw** [msgpack/msgpack#339]
> In timestamp 64 and timestamp 96 formats, nanoseconds must not be larger than 999999999.

Currently the spec states that nanoseconds must not be larger than or equal to 1 billion.

During leap seconds, nanoseconds extends to just under 2 billion nanoseconds. (See: https://github.com/chronotope/chrono/blob/081c6482bc1ca1a3f0e54532a892a377d28bb999/src/naive/time/mod.rs#L472)

In the current message pack protocol spec timestamps of those leap seconds are invalid.

Since 30 bits can only hold 1073741823, anything above that will require timestamp 96 to encode.

**Comment by junderw** [comment]
According to this: https://www.timeanddate.com/time/leapseconds.html

The last leap second was over 7 years ago, and a lot of people are moving to abolish them.

Interesting.

**Comment by methane** [comment]
> During leap seconds, nanoseconds extends to just under 2 billion nanoseconds. (See: https://github.com/chronotope/chrono/blob/081c6482bc1ca1a3f0e54532a892a377d28bb999/src/naive/time/mod.rs#L472)

It is just a chrono's leap second representation. There is no 2 billion nanoseconds in UTC. Leap second is 23:59:60.000-999, not 23:59:59.1000-1999. (See https://en.wikipedia.org/wiki/Leap_second#Process)

Additionally, msgpack timestamp represents Unix timestamp, not UTC. There is no leap second in Unix timestamp.
You need to use some algorithm like [smear](https://developers.google.com/time/smear) to map leap second into unix timestamp.

**Comment by junderw** [comment]
> It is just a chrono's leap second representation. There is no 2 billion nanoseconds in UTC. Leap second is 23:59:60.000-999, not 23:59:59.1000-1999. (See https://en.wikipedia.org/wiki/Leap_second#Process)

So I guess for my PR here, if nsecs is 1 billion or over, I should modulo by one billion and add 1 to the secs value, I guess? To account for `chrono`'s weird representation of the leap second.

https://github.com/3Hren/msgpack-rust/pull/351

Either way, it seems my issue is incorrect. Thanks for the clarification.

**Comment by methane** [comment]
You should follow what chrono does when creating (Unix) timestamp.
https://github.com/chronotope/chrono/blob/081c6482bc1ca1a3f0e54532a892a377d28bb999/src/datetime/mod.rs#L350-L364
